In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import accuracy_score,classification_report


In [2]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 6489-7534

 Directory of C:\Users\Dell\Desktop\New folder

14-01-2023  17:14    <DIR>          .
14-01-2023  12:23    <DIR>          ..
14-01-2023  17:04    <DIR>          .ipynb_checkpoints
28-12-2022  13:08             2,436 50_Startups (1).csv
26-12-2022  17:18             2,436 50_Startups.csv
11-01-2023  21:19           754,033 50strtup.ipynb
14-01-2023  16:32            46,094 assbook.csv
14-01-2023  12:55         2,702,875 ASSIGNMENT SOLUTION PRIYANKA.zip
14-01-2023  16:43           195,292 association book.ipynb
14-01-2023  16:14           189,834 Association rules (book).ipynb
14-01-2023  16:14           109,947 Association rules(my movies).ipynb
14-01-2023  16:54           118,154 association.movies.ipynb
14-01-2023  17:01            72,947 Bank_LR _test.ipynb
14-01-2023  17:02            72,685 Bank_LR.ipynb
29-12-2022  16:49         4,610,348 bank-full.csv
03-01-2023  17:13           536,483 book (1).csv
14-01-2023  

In [3]:
bank=pd.read_csv("bank-full.csv",";")
bank.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [4]:
bank.shape

(45211, 17)

In [5]:
bank.isna().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [6]:
bank['y'].value_counts()

no     39922
yes     5289
Name: y, dtype: int64

In [7]:
bank.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [8]:
bank.y.replace(to_replace=['no','yes'],value=[0,1],inplace=True)
bank.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome  y  
0  unknown    5   may       261         1     -1         0  unknown  0  
1  unknown    5   may       151         1     -1         0  unknown  0  
2  unknown    5   may        76         1     -1         0  unknown  0  
3  unknown    5   may        92         1     -1         0  unknown  0  
4  unknown    5   may       198         1     -1         0  unknown  0

In [9]:
b1=bank[['y','age','job','marital','education','default','balance','housing','loan','contact','day','month','duration','campaign','pdays','previous','poutcome']]

In [10]:
bank1=pd.get_dummies(b1,columns=["age","job","marital","education","default","housing","loan","contact","month","poutcome"])
bank1

y  balance  day  duration  campaign  pdays  previous  age_18  age_19  \
0      0     2143    5       261         1     -1         0       0       0   
1      0       29    5       151         1     -1         0       0       0   
2      0        2    5        76         1     -1         0       0       0   
3      0     1506    5        92         1     -1         0       0       0   
4      0        1    5       198         1     -1         0       0       0   
...   ..      ...  ...       ...       ...    ...       ...     ...     ...   
45206  1      825   17       977         3     -1         0       0       0   
45207  1     1729   17       456         2     -1         0       0       0   
45208  1     5715   17      1127         5    184         3       0       0   
45209  0      668   17       508         4     -1         0       0       0   
45210  0     2971   17       361         2    188        11       0       0   

       age_20  ...  month_jun  month_mar  month_may  month_nov  month_oct  \
0           0  ...          0          0          1          0          0   
1           0  ...          0          0          1          0          0   
2           0  ...          0          0          1          0          0   
3           0  ...          0          0          1          0          0   
4           0  ...          0          0          1          0          0   
...       ...  ...        ...        ...        ...        ...        ...   
45206       0  ...          0          0          0          1          0   
45207       0  ...          0          0          0          1          0   
45208       0  ...          0          0          0          1          0   
45209       0  ...          0          0          0          1          0   
45210       0  ...          0          0          0          1          0   

       month_sep  poutcome_failure  poutcome_other  poutcome_success  \
0              0                 0               0                 0   
1              0                 0               0                 0   
2              0                 0               0                 0   
3              0                 0               0                 0   
4              0                 0               0                 0   
...          ...               ...             ...               ...   
45206          0                 0               0                 0   
45207          0                 0               0                 0   
45208          0                 0               0                 1   
45209          0                 0               0                 0   
45210          0                 0               1                 0   

       poutcome_unknown  
0                     1  
1                     1  
2                     1  
3                     1  
4                     1  
...                 ...  
45206                 1  
45207                 1  
45208                 0  
45209                 1  
45210                 0  

[45211 rows x 128 columns]

# Building a Logistic Regression Model

In [11]:
X = bank1.iloc[:,1::]
Y = bank1.iloc[:,0]

In [12]:
X

balance  day  duration  campaign  pdays  previous  age_18  age_19  \
0         2143    5       261         1     -1         0       0       0   
1           29    5       151         1     -1         0       0       0   
2            2    5        76         1     -1         0       0       0   
3         1506    5        92         1     -1         0       0       0   
4            1    5       198         1     -1         0       0       0   
...        ...  ...       ...       ...    ...       ...     ...     ...   
45206      825   17       977         3     -1         0       0       0   
45207     1729   17       456         2     -1         0       0       0   
45208     5715   17      1127         5    184         3       0       0   
45209      668   17       508         4     -1         0       0       0   
45210     2971   17       361         2    188        11       0       0   

       age_20  age_21  ...  month_jun  month_mar  month_may  month_nov  \
0           0       0  ...          0          0          1          0   
1           0       0  ...          0          0          1          0   
2           0       0  ...          0          0          1          0   
3           0       0  ...          0          0          1          0   
4           0       0  ...          0          0          1          0   
...       ...     ...  ...        ...        ...        ...        ...   
45206       0       0  ...          0          0          0          1   
45207       0       0  ...          0          0          0          1   
45208       0       0  ...          0          0          0          1   
45209       0       0  ...          0          0          0          1   
45210       0       0  ...          0          0          0          1   

       month_oct  month_sep  poutcome_failure  poutcome_other  \
0              0          0                 0               0   
1              0          0                 0               0   
2              0          0                 0               0   
3              0          0                 0               0   
4              0          0                 0               0   
...          ...        ...               ...             ...   
45206          0          0                 0               0   
45207          0          0                 0               0   
45208          0          0                 0               0   
45209          0          0                 0               0   
45210          0          0                 0               1   

       poutcome_success  poutcome_unknown  
0                     0                 1  
1                     0                 1  
2                     0                 1  
3                     0                 1  
4                     0                 1  
...                 ...               ...  
45206                 0                 1  
45207                 0                 1  
45208                 1                 0  
45209                 0                 1  
45210                 0                 0  

[45211 rows x 127 columns]

In [13]:
Y

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int64

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn import preprocessing
from sklearn import metrics
import numpy as np

In [19]:
model = LogisticRegression()
model.fit(X,Y)

LogisticRegression()

In [20]:
model.intercept_

array([-0.62165836])

In [21]:
np.round(model.coef_,2)

array([[ 0.  , -0.  ,  0.  , -0.1 ,  0.  ,  0.01,  0.  ,  0.  ,  0.  ,
         0.01,  0.01,  0.01,  0.01,  0.02, -0.  , -0.  ,  0.  , -0.01,
        -0.02, -0.04, -0.04, -0.04, -0.04, -0.03, -0.03, -0.04, -0.03,
        -0.04, -0.05, -0.03, -0.03, -0.03, -0.03, -0.03, -0.02, -0.02,
        -0.03, -0.01, -0.03, -0.02, -0.02, -0.02, -0.01, -0.02, -0.02,
        -0.02, -0.02, -0.02,  0.  ,  0.02,  0.01,  0.01,  0.01,  0.  ,
         0.01,  0.01,  0.01,  0.  ,  0.  ,  0.01,  0.01,  0.01,  0.  ,
         0.  ,  0.01,  0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.  ,
         0.  ,  0.  ,  0.  ,  0.  , -0.  , -0.  ,  0.  ,  0.  ,  0.  ,
        -0.  ,  0.  , -0.05, -0.32, -0.05, -0.04, -0.04,  0.07, -0.03,
        -0.11,  0.07, -0.1 , -0.01, -0.01, -0.1 , -0.47, -0.05, -0.2 ,
        -0.4 , -0.  , -0.02, -0.58, -0.04,  0.18, -0.81, -0.31, -0.31,
        -0.02,  0.  , -0.61,  0.05, -0.02,  0.03, -0.08, -0.02, -0.13,
        -0.15,  0.1 , -0.5 , -0.1 ,  0.11,  0.08, -0.19, -0.03,  0.36,
      

In [23]:
y_pred = model.predict(X)

In [24]:
y_pred_df = pd.DataFrame({'actual':Y,
                          'predicted_values':model.predict(X)})

In [26]:
y_pred_df

actual  predicted_values
0           0                 0
1           0                 0
2           0                 0
3           0                 0
4           0                 0
...       ...               ...
45206       1                 1
45207       1                 0
45208       1                 1
45209       0                 0
45210       0                 0

[45211 rows x 2 columns]

In [27]:
y_pred_df["actual"].value_counts()

0    39922
1     5289
Name: actual, dtype: int64

In [28]:
y_pred_df["predicted_values"].value_counts()

0    43187
1     2024
Name: predicted_values, dtype: int64

In [29]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as ac
confusion_matrix = confusion_matrix(Y,y_pred)
print(confusion_matrix)

[[39146   776]
 [ 4041  1248]]


In [30]:
ac(Y,y_pred)

0.8934551326004734

In [31]:
#Classification Report
print(classification_report(Y,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94     39922
           1       0.62      0.24      0.34      5289

    accuracy                           0.89     45211
   macro avg       0.76      0.61      0.64     45211
weighted avg       0.87      0.89      0.87     45211



# Prediction using Test and Train model

In [32]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=12)
model = LogisticRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [33]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94     11990
           1       0.62      0.23      0.34      1574

    accuracy                           0.89     13564
   macro avg       0.76      0.61      0.64     13564
weighted avg       0.87      0.89      0.87     13564



In [34]:
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree

In [35]:
model = DecisionTreeClassifier(criterion = 'gini',min_samples_split=5,max_depth=10)
model.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=10, min_samples_split=5)

In [36]:
y_pred=model.predict(x_test)

In [37]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.96      0.94     11990
           1       0.60      0.44      0.51      1574

    accuracy                           0.90     13564
   macro avg       0.76      0.70      0.73     13564
weighted avg       0.89      0.90      0.89     13564

